# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal",
                    models.CharField(
                        choices=[
                            ("sale", "Sotib olish"),
                            ("new", "Yangi binolar"),
                            ("rent", "Uzoq muddat ijara"),
                            ("daily", "Kunlik ijara"),
                            ("commercial", "Tijorat"),
                            ("land", "Yer uchastkasi"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Kvartira", "Kvartira"),
                            ("Hovli uy", "Hovli uy"),
                            ("Tijorat", "Tijorat"),
                            ("Yer uchastkasi", "Yer uchastkasi"),
                            ("Ofis", "Ofis"),
                            ("Ombor", "Ombor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("negotiable", models.BooleanField(default=False)),
                ("mortgage_allowed", models.BooleanField(default=True)),
                ("swap_allowed", models.BooleanField(default=False)),
                ("rooms", models.PositiveSmallIntegerField(default=0)),
                ("area", models.DecimalField(decimal_places=1, max_digits=8)),
                ("floor", models.PositiveSmallIntegerField(default=0)),
                ("floors", models.PositiveSmallIntegerField(default=0)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=64)),
                ("mahalla", models.CharField(blank=True, max_length=120)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("address_hidden", models.BooleanField(default=True)),
                ("metro_name", models.CharField(blank=True, max_length=64)),
                (
                    "metro_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("moderation", "Moderatsiyada"),
                            ("active", "Faol"),
                            ("archived", "Arxivlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("verified_owner", models.BooleanField(default=False)),
                (
                    "cadastre_doc",
                    models.FileField(blank=True, null=True, upload_to="cadastre/"),
                ),
                ("top_until", models.DateTimeField(blank=True, null=True)),
                ("hot_until", models.DateTimeField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="agencies.agency",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="geo.city",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="geo.district",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/%Y/%m/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price histories",
                "ordering": ["changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "deal", "district"],
                name="listings_li_status_0285e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "city"], name="listings_li_status_1fc226_idx"
            ),
        ),
    ]
