services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: uyim
      POSTGRES_USER: uyim
      POSTGRES_PASSWORD: uyim
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://uyim:uyim@db:5432/uyim
      REDIS_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "False"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://uyim:uyim@db:5432/uyim
      REDIS_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "False"
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://uyim:uyim@db:5432/uyim
      REDIS_URL: redis://redis:6379/0
      CELERY_TASK_ALWAYS_EAGER: "False"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
