# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="developer_logos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="developers",
                        to="geo.city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("planned", "Qurilish boshlanmagan"),
                            ("in_progress", "Qurilish jarayonida"),
                            ("completed", "Qurilish tugagan"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                (
                    "completion_label",
                    models.CharField(
                        blank=True, help_text="masalan: 2026 Q3", max_length=32
                    ),
                ),
                (
                    "price_from_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("installment_available", models.BooleanField(default=False)),
                ("tour_3d_url", models.URLField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="geo.city",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="developers.developer",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="geo.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
