# Generated by Django 5.2.17 on 2026-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="channel",
            field=models.CharField(
                choices=[("sms", "SMS"), ("telegram", "Telegram")],
                default="sms",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="link_token",
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
