# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("top", "TOP joylashuv"),
                            ("hot", "HOT belgisi"),
                            ("tg_push", "Telegram push"),
                            ("banner", "Banner reklama"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("payme", "Payme"), ("click", "Click")],
                        default="payme",
                        max_length=16,
                    ),
                ),
                ("price_uzs", models.PositiveIntegerField()),
                ("payment_id", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To'lov kutilmoqda"),
                            ("paid", "To'landi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boost_orders",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClickTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click_trans_id", models.CharField(max_length=32)),
                ("click_paydoc_id", models.CharField(blank=True, max_length=32)),
                ("amount", models.PositiveIntegerField(help_text="so'm")),
                ("prepared", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_transactions",
                        to="payments.boostorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paycom_transaction_id", models.CharField(max_length=32, unique=True)),
                ("amount", models.PositiveIntegerField(help_text="tiyin")),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Yaratildi"),
                            (2, "Bajarildi"),
                            (-1, "Bekor (yaratilgandan keyin)"),
                            (-2, "Bekor (bajarilgandan keyin)"),
                        ],
                        default=1,
                    ),
                ),
                ("reason", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payme_transactions",
                        to="payments.boostorder",
                    ),
                ),
            ],
        ),
    ]
