# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("zoom", models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=48, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="geo.city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mahalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mahallas",
                        to="geo.district",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mahallas",
                "ordering": ["name"],
                "unique_together": {("district", "name")},
            },
        ),
    ]
