# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="STIR/INN"
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="agency_licenses/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("years", models.PositiveSmallIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("founded_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agencies",
                "ordering": ["-verified", "-rating"],
            },
        ),
    ]
