# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Yillik foiz, %"
                    ),
                ),
                (
                    "min_down_pct",
                    models.PositiveSmallIntegerField(
                        verbose_name="Min. boshlang'ich to'lov, %"
                    ),
                ),
                (
                    "max_term_years",
                    models.PositiveSmallIntegerField(verbose_name="Max. muddat, yil"),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["rate"],
            },
        ),
        migrations.CreateModel(
            name="MortgageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("down_pct", models.PositiveSmallIntegerField()),
                ("years", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("review", "Ko'rib chiqilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="mortgage.bank",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortgage_applications",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
