# Generated by Django 5.2.17 on 2026-09-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        ("geo", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="@chilonzor_uylar", max_length=64, unique=True
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Bot admin qilingach to'ldiriladi",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_channels",
                        to="agencies.agency",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_channels",
                        to="geo.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Navbatda"),
                            ("posted", "Joylandi"),
                            ("failed", "Xatolik"),
                            ("sold", "Sotildi belgisi qo'yildi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="telegrambot.telegramchannel",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_posts",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "unique_together": {("listing", "channel")},
            },
        ),
    ]
